steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cloud-run-googlesheet-rest-api:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/cloud-run-googlesheet-rest-api:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'run', 'deploy', 'cloud-run-googlesheet-rest-api', '--region=europe-west1', '--platform=managed', '--image=gcr.io/$PROJECT_ID/cloud-run-googlesheet-rest-api:$SHORT_SHA']
