apiVersion: v1
kind: Service
metadata:
  labels:
    app: config
  name: config-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: config
  type: LoadBalancer
